name = "hijri-birthday"
compatibility_date = "2025-07-17"
workers_dev = false

route = { pattern = "hijri-birthday.h2.limited", custom_domain = true }

[assets]
directory = "./dist/"
not_found_handling = "single-page-application"
