/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as MonthsRouteImport } from './routes/months'
import { Route as GuidanceRouteImport } from './routes/guidance'
import { Route as AddRouteImport } from './routes/add'
import { Route as RecordedRouteRouteImport } from './routes/recorded/route'
import { Route as IndexRouteRouteImport } from './routes/index/route'

const MonthsRoute = MonthsRouteImport.update({
  id: '/months',
  path: '/months',
  getParentRoute: () => rootRouteImport,
} as any)
const GuidanceRoute = GuidanceRouteImport.update({
  id: '/guidance',
  path: '/guidance',
  getParentRoute: () => rootRouteImport,
} as any)
const AddRoute = AddRouteImport.update({
  id: '/add',
  path: '/add',
  getParentRoute: () => rootRouteImport,
} as any)
const RecordedRouteRoute = RecordedRouteRouteImport.update({
  id: '/recorded',
  path: '/recorded',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRouteRoute = IndexRouteRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRouteRoute
  '/recorded': typeof RecordedRouteRoute
  '/add': typeof AddRoute
  '/guidance': typeof GuidanceRoute
  '/months': typeof MonthsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRouteRoute
  '/recorded': typeof RecordedRouteRoute
  '/add': typeof AddRoute
  '/guidance': typeof GuidanceRoute
  '/months': typeof MonthsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRouteRoute
  '/recorded': typeof RecordedRouteRoute
  '/add': typeof AddRoute
  '/guidance': typeof GuidanceRoute
  '/months': typeof MonthsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/recorded' | '/add' | '/guidance' | '/months'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/recorded' | '/add' | '/guidance' | '/months'
  id: '__root__' | '/' | '/recorded' | '/add' | '/guidance' | '/months'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRouteRoute: typeof IndexRouteRoute
  RecordedRouteRoute: typeof RecordedRouteRoute
  AddRoute: typeof AddRoute
  GuidanceRoute: typeof GuidanceRoute
  MonthsRoute: typeof MonthsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/months': {
      id: '/months'
      path: '/months'
      fullPath: '/months'
      preLoaderRoute: typeof MonthsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/guidance': {
      id: '/guidance'
      path: '/guidance'
      fullPath: '/guidance'
      preLoaderRoute: typeof GuidanceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/add': {
      id: '/add'
      path: '/add'
      fullPath: '/add'
      preLoaderRoute: typeof AddRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/recorded': {
      id: '/recorded'
      path: '/recorded'
      fullPath: '/recorded'
      preLoaderRoute: typeof RecordedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRouteRoute: IndexRouteRoute,
  RecordedRouteRoute: RecordedRouteRoute,
  AddRoute: AddRoute,
  GuidanceRoute: GuidanceRoute,
  MonthsRoute: MonthsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
