/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as RecordedRouteImport } from './routes/recorded'
import { Route as MonthsRouteImport } from './routes/months'
import { Route as GuidanceRouteImport } from './routes/guidance'
import { Route as AddRouteImport } from './routes/add'
import { Route as IndexRouteImport } from './routes/index'

const RecordedRoute = RecordedRouteImport.update({
  id: '/recorded',
  path: '/recorded',
  getParentRoute: () => rootRouteImport,
} as any)
const MonthsRoute = MonthsRouteImport.update({
  id: '/months',
  path: '/months',
  getParentRoute: () => rootRouteImport,
} as any)
const GuidanceRoute = GuidanceRouteImport.update({
  id: '/guidance',
  path: '/guidance',
  getParentRoute: () => rootRouteImport,
} as any)
const AddRoute = AddRouteImport.update({
  id: '/add',
  path: '/add',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/add': typeof AddRoute
  '/guidance': typeof GuidanceRoute
  '/months': typeof MonthsRoute
  '/recorded': typeof RecordedRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/add': typeof AddRoute
  '/guidance': typeof GuidanceRoute
  '/months': typeof MonthsRoute
  '/recorded': typeof RecordedRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/add': typeof AddRoute
  '/guidance': typeof GuidanceRoute
  '/months': typeof MonthsRoute
  '/recorded': typeof RecordedRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/add' | '/guidance' | '/months' | '/recorded'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/add' | '/guidance' | '/months' | '/recorded'
  id: '__root__' | '/' | '/add' | '/guidance' | '/months' | '/recorded'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AddRoute: typeof AddRoute
  GuidanceRoute: typeof GuidanceRoute
  MonthsRoute: typeof MonthsRoute
  RecordedRoute: typeof RecordedRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/recorded': {
      id: '/recorded'
      path: '/recorded'
      fullPath: '/recorded'
      preLoaderRoute: typeof RecordedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/months': {
      id: '/months'
      path: '/months'
      fullPath: '/months'
      preLoaderRoute: typeof MonthsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/guidance': {
      id: '/guidance'
      path: '/guidance'
      fullPath: '/guidance'
      preLoaderRoute: typeof GuidanceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/add': {
      id: '/add'
      path: '/add'
      fullPath: '/add'
      preLoaderRoute: typeof AddRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AddRoute: AddRoute,
  GuidanceRoute: GuidanceRoute,
  MonthsRoute: MonthsRoute,
  RecordedRoute: RecordedRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
